#!/usr/bin/env unishell
echo "================"
echo $SCRIPT_NAME
echo "================"

#NOTE: $() is just short for eval

#sanity check
echo a
echo "hello"
echo a b
echo "hello" "world"

#
echo $(echo a)

#
echo $(echo a) $(echo b)
echo $(echo "hello") $(echo "world")

#Subst inside quotes

echo "$(echo a)"



#
$("abc")
$("1")
$("+1")
$("-1")
$("$(+1)")
$("$(-1)")
$(1)
$(+1)
$(-1)
$(-1.1e-1)
$(+1.1e+1)

#
"$(1)"
"$(+1)"
"$(-1)"
"$(-1.1e-1)"
"$(+1.1e+1)"



#TODO: Uncomment when string escapes are supported
#echo "$(echo \"$(echo a)\")"